name: worker_manager
version: 3.4.0
description: Executor allows you to create a queue of tasks for isolate pool
homepage: "https://github.com/Renesanse/worker_manager"

dependencies:
  async: ^2.5.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0

environment:
  sdk: '>=2.12.0 <3.0.0'
